import { useEffect, useState } from "react";
const categories=["Network","Windows","Linux","Application","Account","Hardware","Other"],blank={title:"",problem:"",symptoms:"",steps:"",category:"Network",platform:""};
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options});if(response.status===204)return null;const data=await response.json();if(!response.ok)throw new Error(data.details?.join(", ")||data.message||"Request failed");return data}
export default function App(){const [articles,setArticles]=useState([]),[stats,setStats]=useState({}),[form,setForm]=useState(blank),[filters,setFilters]=useState({category:"",verified:"",search:""}),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v)).toString();const [list,totals]=await Promise.all([api(`/api/articles${q?`?${q}`:""}`),api("/api/articles/stats")]);setArticles(list);setStats(totals);setError("")}catch(err){setError(err.message)}finally{setLoading(false)}}; useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[filters.category,filters.verified,filters.search]);
 const submit=async e=>{e.preventDefault();try{await api("/api/articles",{method:"POST",body:JSON.stringify({...form,symptoms:form.symptoms.split("\n").filter(Boolean),steps:form.steps.split("\n").filter(Boolean)})});setForm(blank);await load()}catch(err){setError(err.message)}}; const change=async(id,data,path="")=>{try{await api(`/api/articles/${id}${path}`,{method:path?"POST":"PATCH",body:path?undefined:JSON.stringify(data)});await load()}catch(err){setError(err.message)}}; const remove=async id=>{if(!confirm("Delete this article?"))return;try{await api(`/api/articles/${id}`,{method:"DELETE"});await load()}catch(err){setError(err.message)}};
 return <main className="shell"><header><p>SUPPORT KNOWLEDGE BASE</p><h1>Support<span>Scribe</span></h1><small>Turn solved tickets into reliable answers.</small></header><section className="stats">{["total","verified","helpfulVotes","categoryCoverage"].map(k=><article key={k}><b>{stats[k]||0}</b><small>{k.replace(/([A-Z])/g," $1")}</small></article>)}</section>
 <form className="form" onSubmit={submit}><input required minLength="5" placeholder="Article title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required minLength="10" placeholder="Problem statement" value={form.problem} onChange={e=>setForm({...form,problem:e.target.value})}/><textarea required placeholder="Symptoms, one per line" value={form.symptoms} onChange={e=>setForm({...form,symptoms:e.target.value})}/><textarea required placeholder="Resolution steps, one per line" value={form.steps} onChange={e=>setForm({...form,steps:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select><input required minLength="2" placeholder="Platform" value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}/><button>Publish fix</button></form>
 <div className="filters"><input placeholder="Search problem or symptom" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="">All categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select value={filters.verified} onChange={e=>setFilters({...filters,verified:e.target.value})}><option value="">All articles</option><option value="true">Verified</option><option value="false">Unverified</option></select></div>
 {error&&<p className="error" role="alert">{error}</p>}{loading?<p>Loading fixes…</p>:<section className="grid">{articles.map(a=><article className="card" key={a._id}><div><span>{a.category}</span><b>{a.verified?"✓ Verified":"Draft"}</b></div><h2>{a.title}</h2><p>{a.problem}</p><details><summary>Symptoms & resolution</summary><h3>Symptoms</h3><ul>{a.symptoms.map(x=><li key={x}>{x}</li>)}</ul><h3>Steps</h3><ol>{a.steps.map((x,i)=><li key={`${i}-${x}`}>{x}</li>)}</ol></details><small>{a.platform} · {a.helpfulCount} helpful</small><footer><button onClick={()=>change(a._id,{verified:!a.verified})}>{a.verified?"Unverify":"Verify"}</button><button onClick={()=>change(a._id,null,"/helpful")}>Helpful +1</button><button className="delete" onClick={()=>remove(a._id)}>Delete</button></footer></article>)}{!articles.length&&<p>No articles match.</p>}</section>}</main>}

