import { useEffect, useState } from "react";
const types=["Laptop","Desktop","Monitor","Phone","Router","Printer","Other"],statuses=["Available","Assigned","Repair","Retired"],conditions=["Excellent","Good","Fair","Poor"];
const blank={name:"",serialNumber:"",type:"Laptop",status:"Available",condition:"Good",assignedTo:"",location:"",warrantyUntil:"",nextService:"",notes:""};
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options});if(response.status===204)return null;const data=await response.json();if(!response.ok)throw new Error(data.details?.join(", ")||data.message||"Request failed");return data}
export default function App(){
 const [assets,setAssets]=useState([]),[stats,setStats]=useState({}),[form,setForm]=useState(blank),[filters,setFilters]=useState({status:"",type:"",search:""}),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v)).toString();const [items,totals]=await Promise.all([api(`/api/assets${query?`?${query}`:""}`),api("/api/assets/stats")]);setAssets(items);setStats(totals);setError("")}catch(err){setError(err.message)}finally{setLoading(false)}};
 useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[filters.status,filters.type,filters.search]);
 const submit=async event=>{event.preventDefault();try{await api("/api/assets",{method:"POST",body:JSON.stringify(form)});setForm(blank);await load()}catch(err){setError(err.message)}};
 const update=async(id,changes)=>{try{await api(`/api/assets/${id}`,{method:"PATCH",body:JSON.stringify(changes)});await load()}catch(err){setError(err.message)}};
 const remove=async id=>{if(!window.confirm("Delete this asset?"))return;try{await api(`/api/assets/${id}`,{method:"DELETE"});await load()}catch(err){setError(err.message)}};
 return <main className="shell"><header><p>IT INVENTORY CONTROL</p><h1>Asset<span>Pulse</span></h1><small>Know what you own, where it is, and what needs attention.</small></header>
 <section className="stats">{["total","assigned","repair","expiredWarranty","serviceDue"].map(key=><article key={key}><b>{stats[key]||0}</b><small>{key.replace(/([A-Z])/g," $1")}</small></article>)}</section>
 <form className="form" onSubmit={submit}><input required minLength="2" placeholder="Asset name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required pattern="[A-Za-z0-9._/-]{3,60}" placeholder="Serial number" value={form.serialNumber} onChange={e=>setForm({...form,serialNumber:e.target.value})}/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select><select value={form.condition} onChange={e=>setForm({...form,condition:e.target.value})}>{conditions.map(x=><option key={x}>{x}</option>)}</select><input required placeholder="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><input required={form.status==="Assigned"} placeholder="Assigned to" value={form.assignedTo} onChange={e=>setForm({...form,assignedTo:e.target.value})}/><label>Warranty<input type="date" value={form.warrantyUntil} onChange={e=>setForm({...form,warrantyUntil:e.target.value})}/></label><label>Next service<input type="date" value={form.nextService} onChange={e=>setForm({...form,nextService:e.target.value})}/></label><button>Add asset</button></form>
 <div className="filters"><input placeholder="Search name, serial, assignee" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="">All types</option>{types.map(x=><option key={x}>{x}</option>)}</select></div>
 {error&&<p className="error" role="alert">{error}</p>}{loading?<p>Loading assets…</p>:<section className="grid">{assets.map(asset=><article className="card" key={asset._id}><div><span className="tag">{asset.type}</span><span className={`status ${asset.status.toLowerCase()}`}>{asset.status}</span></div><h2>{asset.name}</h2><code>{asset.serialNumber}</code><p>{asset.location}{asset.assignedTo?` · ${asset.assignedTo}`:""}</p><small>{asset.condition} condition</small><footer><select value={asset.status} onChange={e=>update(asset._id,{status:e.target.value,assignedTo:asset.assignedTo})}>{statuses.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>remove(asset._id)}>Delete</button></footer></article>)}{!assets.length&&<p>No assets match.</p>}</section>}</main>
}

