import { useEffect, useState } from "react";
const topics=["JavaScript","React","Node","MongoDB","Python","SQL","Networking","QA","HR","Other"];
const levels=["New","Learning","Confident","Mastered"];
const today=()=>new Date().toISOString().slice(0,10);
const blank=()=>({question:"",answer:"",topic:"JavaScript",confidence:"New",nextReview:today(),bookmarked:false});
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options});if(response.status===204)return null;const data=await response.json();if(!response.ok)throw new Error(data.details?.join(", ")||data.message||"Request failed");return data}
export default function App(){
  const [cards,setCards]=useState([]),[stats,setStats]=useState({}),[form,setForm]=useState(blank()),[filters,setFilters]=useState({topic:"",confidence:"",due:"",search:""}),[open,setOpen]=useState({}),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);try{const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v)).toString();const [list,totals]=await Promise.all([api(`/api/cards${query?`?${query}`:""}`),api("/api/cards/stats")]);setCards(list);setStats(totals);setError("")}catch(err){setError(err.message)}finally{setLoading(false)}};
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[filters.topic,filters.confidence,filters.due,filters.search]);
  const submit=async event=>{event.preventDefault();try{await api("/api/cards",{method:"POST",body:JSON.stringify(form)});setForm(blank());await load()}catch(err){setError(err.message)}};
  const change=async(id,changes)=>{try{await api(`/api/cards/${id}`,{method:"PATCH",body:JSON.stringify(changes)});await load()}catch(err){setError(err.message)}};
  const remove=async id=>{if(!window.confirm("Delete this interview card?"))return;try{await api(`/api/cards/${id}`,{method:"DELETE"});await load()}catch(err){setError(err.message)}};
  return <main className="shell"><header><p>FOCUSED INTERVIEW PRACTICE</p><h1>Interview<span>Deck</span></h1><small>Turn difficult questions into confident answers.</small></header>
    <section className="stats">{["total","due","weak","mastered"].map(key=><article key={key}><b>{stats[key]||0}</b><small>{key}</small></article>)}</section>
    <form className="form" onSubmit={submit}><input required minLength="5" maxLength="300" placeholder="Interview question" value={form.question} onChange={e=>setForm({...form,question:e.target.value})}/><textarea required minLength="10" maxLength="2000" placeholder="Strong answer" value={form.answer} onChange={e=>setForm({...form,answer:e.target.value})}/><select value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}>{topics.map(x=><option key={x}>{x}</option>)}</select><select value={form.confidence} onChange={e=>setForm({...form,confidence:e.target.value})}>{levels.map(x=><option key={x}>{x}</option>)}</select><label>Next review<input required type="date" value={form.nextReview} onChange={e=>setForm({...form,nextReview:e.target.value})}/></label><button>Add card</button></form>
    <div className="filters"><input placeholder="Search questions" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><select value={filters.topic} onChange={e=>setFilters({...filters,topic:e.target.value})}><option value="">All topics</option>{topics.map(x=><option key={x}>{x}</option>)}</select><select value={filters.confidence} onChange={e=>setFilters({...filters,confidence:e.target.value})}><option value="">All levels</option>{levels.map(x=><option key={x}>{x}</option>)}</select><label><input type="checkbox" checked={filters.due==="true"} onChange={e=>setFilters({...filters,due:e.target.checked?"true":""})}/> Due only</label></div>
    {error&&<p className="error" role="alert">{error}</p>}{loading?<p>Loading cards…</p>:<section className="grid">{cards.map(card=><article className="card" key={card._id}><div className="meta"><span>{card.topic}</span><button title="Bookmark" onClick={()=>change(card._id,{bookmarked:!card.bookmarked})}>{card.bookmarked?"★":"☆"}</button></div><h2>{card.question}</h2>{open[card._id]?<p className="answer">{card.answer}</p>:<button className="reveal" onClick={()=>setOpen({...open,[card._id]:true})}>Reveal answer</button>}<footer><select value={card.confidence} onChange={e=>change(card._id,{confidence:e.target.value})}>{levels.map(x=><option key={x}>{x}</option>)}</select><input title="Next review" type="date" value={card.nextReview.slice(0,10)} onChange={e=>change(card._id,{nextReview:e.target.value})}/><button className="delete" onClick={()=>remove(card._id)}>Delete</button></footer></article>)}{!cards.length&&<p>No cards match your filters.</p>}</section>}</main>
}

