import { useEffect, useState } from "react";
const zones=["Quiet","Collaboration","Window","Standing"],today=()=>new Date().toISOString().slice(0,10),blank=()=>({employee:"",email:"",desk:"",zone:"Quiet",date:today(),startTime:"09:00",endTime:"17:00",purpose:""});
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options});if(response.status===204)return null;const data=await response.json();if(!response.ok)throw new Error(data.details?.join(", ")||data.message||"Request failed");return data}
export default function App(){const [items,setItems]=useState([]),[stats,setStats]=useState({}),[form,setForm]=useState(blank()),[filters,setFilters]=useState({date:"",zone:"",status:"",search:""}),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v)).toString();const [list,totals]=await Promise.all([api(`/api/reservations${q?`?${q}`:""}`),api("/api/reservations/stats")]);setItems(list);setStats(totals);setError("")}catch(err){setError(err.message)}finally{setLoading(false)}}; useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[filters.date,filters.zone,filters.status,filters.search]);
 const submit=async e=>{e.preventDefault();try{await api("/api/reservations",{method:"POST",body:JSON.stringify(form)});setForm(blank());await load()}catch(err){setError(err.message)}}; const cancel=async id=>{try{await api(`/api/reservations/${id}`,{method:"PATCH",body:JSON.stringify({status:"Cancelled"})});await load()}catch(err){setError(err.message)}}; const remove=async id=>{if(!confirm("Delete reservation?"))return;try{await api(`/api/reservations/${id}`,{method:"DELETE"});await load()}catch(err){setError(err.message)}};
 return <main className="shell"><header><p>FLEXIBLE WORKSPACE</p><h1>Desk<span>Reserve</span></h1><small>Choose a desk. Protect your focus. Avoid booking conflicts.</small></header><section className="stats">{["total","today","upcoming","cancelled"].map(k=><article key={k}><b>{stats[k]||0}</b><small>{k}</small></article>)}</section>
 <form className="form" onSubmit={submit}><input required minLength="2" placeholder="Employee name" value={form.employee} onChange={e=>setForm({...form,employee:e.target.value})}/><input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required pattern="[A-Za-z0-9-]{2,20}" placeholder="Desk e.g. Q-12" value={form.desk} onChange={e=>setForm({...form,desk:e.target.value})}/><select value={form.zone} onChange={e=>setForm({...form,zone:e.target.value})}>{zones.map(x=><option key={x}>{x}</option>)}</select><input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><input required type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/><input required type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/><input maxLength="200" placeholder="Purpose" value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/><button>Reserve</button></form>
 <div className="filters"><input placeholder="Search employee or desk" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><input type="date" value={filters.date} onChange={e=>setFilters({...filters,date:e.target.value})}/><select value={filters.zone} onChange={e=>setFilters({...filters,zone:e.target.value})}><option value="">All zones</option>{zones.map(x=><option key={x}>{x}</option>)}</select><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option><option>Confirmed</option><option>Cancelled</option></select></div>
 {error&&<p className="error" role="alert">{error}</p>}{loading?<p>Loading bookings…</p>:<section className="grid">{items.map(x=><article className={`card ${x.status.toLowerCase()}`} key={x._id}><div><span>{x.zone}</span><b>{x.desk}</b></div><h2>{x.employee}</h2><p>{x.date} · {x.startTime}–{x.endTime}</p><small>{x.purpose||x.email}</small><footer>{x.status==="Confirmed"&&<button onClick={()=>cancel(x._id)}>Cancel</button>}<button className="delete" onClick={()=>remove(x._id)}>Delete</button></footer></article>)}{!items.length&&<p>No reservations match.</p>}</section>}</main>}

